[assembly: System.Reflection.AssemblyCompany("Binary Charm Ltd")]
[assembly: System.Reflection.AssemblyTitle("Text Color Buttons Runtime Assembly")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2022.")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("BinaryCharm.UI.TextColorButtons.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.UI")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("TMPro.UI")]
[assembly: UnityEngine.Scripting.Preserve]
